sudo: required
language: ruby

rvm:
  - 2.3.1
  - 2.2
  - 2.1

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgeoip-dev
  - gem update bundler

gemfile:
  - Gemfile
  - gemfiles/fluentd_v0.14.gemfile
